// <auto-generated />
using System;
using BabakBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabakBlog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404100633_SeedingInıtialData")]
    partial class SeedingInıtialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BabakBlog.Models.Kategori", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            id = 1,
                            isim = "Yazılım"
                        },
                        new
                        {
                            id = 2,
                            isim = "Spor"
                        });
                });

            modelBuilder.Entity("BabakBlog.Models.Post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kategoriId")
                        .HasColumnType("int");

                    b.Property<string>("resimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("yayinTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("yazar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("kategoriId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            id = 1,
                            baslik = "C# Nedir?",
                            icerik = "C#, Microsoft tarafından geliştirilen, nesne yönelimli bir programlama dilidir. C# ile masaüstü uygulamaları, web uygulamaları, mobil uygulamalar ve oyunlar geliştirebilirsiniz.",
                            kategoriId = 1,
                            resimUrl = "resim1.jpg",
                            yayinTarih = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            yazar = "Babak Pourkar"
                        },
                        new
                        {
                            id = 2,
                            baslik = "Calisthenics Göğüs Hareketleri",
                            icerik = "Şınav,dips,diamond şınav",
                            kategoriId = 2,
                            resimUrl = "resim2.jpg",
                            yayinTarih = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            yazar = "Babak Pourkar"
                        });
                });

            modelBuilder.Entity("BabakBlog.Models.Yorum", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("postId")
                        .HasColumnType("int");

                    b.Property<DateTime>("yorumTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("postId");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("BabakBlog.Models.Post", b =>
                {
                    b.HasOne("BabakBlog.Models.Kategori", "Kategori")
                        .WithMany("Posts")
                        .HasForeignKey("kategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BabakBlog.Models.Yorum", b =>
                {
                    b.HasOne("BabakBlog.Models.Post", "Post")
                        .WithMany("Yorumlar")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BabakBlog.Models.Kategori", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BabakBlog.Models.Post", b =>
                {
                    b.Navigation("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
